recipes_project/recipes/urls.py
from django.conf.urls import patterns, url
from recipes import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^about/$', views.about, name='about'),
                       url(r'^add_category/$', views.add_category,
                           name='add_category'),
                       url(r'^category/(?P<category_name_url>\w+)/$',
                           views.category, name='category'),
                       url(r'^add_recipe/$',
                           views.add_recipe, name='add_recipe'),
                       url(r'^add_ingredient/$', views.add_ingredient,
                           name='add_ingredient'),
                       url(r'recipe/(?P<recipe_id>\d+)/add_recipe_ingredient/$',
                           views.add_recipe_ingredient, name='add_recipe_ingredient'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^login/$', views.user_login, name='login'),
                       url(r'^restricted/$', views.restricted,
                           name='restricted'),
                       url(r'^logout/$', views.user_logout, name='logout'),
                       url(r'^profile/$', views.profile, name='profile'),
                       url(r'^goto/$', views.track_url, name='track_url'),
                       url(r'^like_category/$', views.like_category,
                           name='like_category'),
                       url(r'^suggest_category/$', views.suggest_category,
                           name='suggest_category'),
                       url(r'^suggest_recipe/$', views.suggest_recipe,
                           name='suggest_recipe'),
                       url(r'^auto_add_recipe/$', views.auto_add_recipe,
                           name='auto_add_recipe'),
                       url(r'^recipe/(?P<recipe_id>\d+)/$',
                           views.show_recipe, name='recipe'),
                       url(r'^recipe/(?P<recipe_id>\d+)/edit/$',
                           views.add_recipe, name='edit_recipe'),
                       )

recipes_project/recipes_project/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'recipes_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('recipes.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
         'serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

recipes_project/recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


# Keep this as category and it only really needs a name
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.name


# Call this model Recipe and give it fields for directions, 
# page source, notes, etc..
class Recipe(models.Model):
    category = models.ForeignKey(Category, help_text="Choose a Category")
    title = models.CharField(max_length=128, help_text="Please enter the title of the recipe.")
    url = models.URLField(help_text="Please enter the URL of the recipe.")
    directions = models.TextField(help_text="Please enter the recipe directions.")
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

class Ingredient(models.Model):
    name = models.CharField(max_length=128,unique=True, help_text="Enter an Ingredient")

    def __unicode__(self):
        return self.name

class Unit(models.Model):
    name = models.CharField(max_length=32, blank=True)

    def __unicode__(self):
        return self.name

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, related_name="ingredients")
    quantity = models.FloatField(default=0.0)
    unit = models.ForeignKey(Unit, blank=True, null=True)
    ingredient = models.ForeignKey(Ingredient)


    def __unicode__(self):
        if not self.unit:
            return "%g %s" % (self.quantity, self.ingredient)
        else:
            return "%g %s %s" % (self.quantity, self.unit, self.ingredient)

# Modify this model to be Ingredients. It should contain,
# fields for quantity, units and name (ex. sugar, salt, water..)
class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaninful!
    def __unicode__(self):
        return self.user.username

recipes_project/recipes/forms.py
from django import forms
from django.utils.translation import ugettext as _
from recipes.models import Recipe, Category, UserProfile, Ingredient, RecipeIngredient
from django.contrib.auth.models import User

class RecipeIngredientForm(forms.ModelForm):

    class Meta:
        model = RecipeIngredient
        fields = ('quantity', 'unit', 'ingredient')
        labels = {
            'unit': _("Unit (optional)"),
        }

class IngredientForm(forms.ModelForm):

    class Meta:
        model = Ingredient
        fields = ('name',)

class CategoryForm(forms.ModelForm):
    name  = forms.CharField(max_length=128, help_text="Please enter a category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category

class RecipeForm(forms.ModelForm):
    #title = forms.CharField(max_length=128, help_text="Please enter the title of the recipe.")
    #directions = forms.CharField(widget=forms.Textarea, help_text="Enter the recipe directions.")
    #url = forms.URLField(max_length=200, help_text="Please enter the URL of the recipe.")
    #views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://', prepend 'http://'
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Recipe

        # Here we are hiding the foreign key.
        fields = ('category', 'title', 'directions', 'url', 'views')

class UserForm(forms.ModelForm):
    username = forms.CharField(help_text="Please enter a username")
    email = forms.CharField(help_text="Please enter your email address")
    password = forms.CharField(widget=forms.PasswordInput(), help_text="Please enter a password")

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(help_text="Please enter your website URL", required=False)
    picture = forms.ImageField(help_text="Select a profile image to upload", required=False)
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

recipes_project/recipes/views.py
from datetime import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from recipes.models import Category, Recipe, UserProfile, Ingredient
from recipes.forms import CategoryForm, RecipeForm, UserForm, UserProfileForm, IngredientForm, RecipeIngredientForm
from recipes.bing_search import run_query


# I definitely want the ability to log in and out so this should stay
# Use the login_required() decorator to ensure only those logged in can access the view
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out
    logout(request)

    #Take the user back to the homepage
    return HttpResponseRedirect(reverse('index'))


# I don't think I need a restricted page for anything
@login_required
def restricted(request):
    context = RequestContext(request)
    cat_list = get_category_list()
    context_dict = {'cat_list': cat_list}

    return render_to_response('recipes/restricted.html', context_dict, context)

# I don't think I need a profile page 
@login_required
def profile(request):
    context = RequestContext(request)
    cat_list = get_category_list()
    context_dict = {'cat_list': cat_list}
    u = User.objects.get(username=request.user)

    try:
        up = UserProfile.objects.get(user=u)
    except:
        up = None

    context_dict['user'] = u
    context_dict['userprofile'] = up
    return render_to_response('recipes/profile.html', context_dict, context)

# I was thinking this would be a good place for recipe ratings instead of likes
@login_required
def like_category(request):
    # context = RequestContext(request)
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']

    likes = 0
    if cat_id:
        category = Category.objects.get(id=int(cat_id))
        if category:
            likes = category.likes + 1
            category.likes = likes
            category.save()

    return HttpResponse(likes)

# I definitely want to be able to add recipes with title, ingredients,
# directions, source, notes and possibly other stuff.
@login_required
def auto_add_recipe(request):
    context = RequestContext(request)
    cat_id = None
    url = None
    title = None
    context_dict = {}
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        url = request.GET['url']
        title = request.GET['title']
        if cat_id:
            category = Category.objects.get(id=int(cat_id))
            Recipe.objects.get_or_create(category=category, title=title, url=url)

            recipes = Recipe.objects.filter(category=category).order_by('-views')

            # Adds our results list to the template context under name pages.
            context_dict['recipes_list'] = recipes

    return render_to_response('recipes/recipe_list.html', context_dict, context)

# I want to be able to search the recipes and have web results returned
# in addition to local recipes.
def search(request):
    context = RequestContext(request)
    cat_list = get_category_list()
    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            # Run our Bing function to get the results list
            result_list = run_query(query)

    context_dict = {'cat_list': cat_list, 'result_list': result_list}

    return render_to_response('recipes/search.html', context_dict, context)

# I don't really remember what this was for
def track_url(request):
    # context = RequestContext(request)
    recipe_id = None
    url = reverse('index')
    if request.method == 'GET':
        if 'recipe_id' in request.GET:
            recipe_id = request.GET['recipe_id']
            try:
                recipe = Recipe.objects.get(id=recipe_id)
                recipe.views = recipe.views + 1
                recipe.save()
                url = recipe.url
            except:
                pass

    return redirect(url)


# I don't really need to list categories by most popular but I guess it wouldn't hurt
def get_category_list(max_results=0, starts_with=''):
        cat_list = []
        if starts_with:
                cat_list = Category.objects.filter(name__istartswith=starts_with)
        else:
                cat_list = Category.objects.all()

        if max_results > 0:
                if len(cat_list) > max_results:
                        cat_list = cat_list[:max_results]

        for cat in cat_list:
                cat.url = encode_url(cat.name)

        return cat_list

# I don't think I need this unless it matters for adding categories
def suggest_category(request):
        context = RequestContext(request)
        cat_list = []
        starts_with = ''
        if request.method == 'GET':
                starts_with = request.GET['suggestion']

        cat_list = get_category_list(8, starts_with)

        return render_to_response('recipes/category_list.html', {'cat_list': cat_list }, context)

def get_recipe_list(max_results=0, is_in='', category_id=None):
        recipe_list = []

        if category_id:
            recipe_list = Recipe.objects.filter(category=category_id)
        else:
            recipe_list = Recipe.objects.all()

        if is_in:
            recipe_list = recipe_list.filter(title__icontains=is_in)

        if max_results > 0:
                if len(recipe_list) > max_results:
                        recipe_list = recipe_list[:max_results]

        return recipe_list

  # I don't think I need this unless it matters for adding categories
def suggest_recipe(request):
        context = RequestContext(request)
        recipe_list = []
        is_in = ''
        category_id = None 
        if request.method == 'GET':
                is_in = request.GET['recipe_suggest']
                try:
                    category_id = request.GET['category_id']
                except:
                    pass

        recipe_list = get_recipe_list(8, is_in, category_id)

        return render_to_response('recipes/recipe_list.html', {'recipe_list': recipe_list }, context)


# Definitely want log in access for add, modify, delete rights
def user_login(request):
    # Like before, obtain the context for the user's request
    context = RequestContext(request)
    cat_list = get_category_list()
    context_dict = {'cat_list': cat_list}

    # If the request is a HTTP POST, try to pull out the relevant info
    if request.method == 'POST':
        # Gather the username and password provided by the user
        # This information is obtained from the login form
        username = request.POST['username']
        password = request.POST['password']

        # Use Django's machinery to attempt to see if the usernam/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found
        if user is not None:
            # Is the account active? It could have been disabled
            if user.is_active:
                # If the account is valid and active, we can log the user in
                # We'll send the user back to the homepage
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your Recipes account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponseRedirect(reverse('login'))

    # The request is not a HTTP POST, so display the login form
    # This scenario would most likely be a HTTP GET
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render_to_response('recipes/login.html', context_dict, context)

# I don't want/need people to be able to register
def register(request):
    #Like before, get the request's context
    context = RequestContext(request)
    cat_list = get_category_list()

    # A boolean value for telling the template whether the registration was successful
    # Set to False initiall. Code changes value to True when registration succeeds
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information
        # Note that we make use of both UserForm and UserProfileForm
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance
            # Since we need to set the user attribute ourselves, we set commit=False
            # This delays saving the model until we're ready to avoid integrity problems
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?

recipes_project/templates/recipes/about.html
{% extends 'recipes/base.html' %}

{% load static %}

{% block body_block %}
<div class="hero-unit">
    <h1 style="font-family:Ubuntu; color: #7a6f66">About Recipes</h1>
    This site is a place for me to keep recipes I find interesting..<br />

    You've visited the site on {{ visits }} occasion(s).<br />
    <img src="{% static "watermelon.jpg" %}" alt="watermelon" />
</div>

{% endblock %}

recipes_project/templates/recipes/add_category.html
{% extends 'recipes/base.html' %}

{% block body_block %}
<div class="hero-unit">
        <h1>Add a Category</h1>
        <br/>
        <div class="container">
        {% if category_name_url %}
            <div style="color: red;">The specified category does not exist!</div>
        {% else %}
            <form class="span6" id="category_form" method="post" action="/add_category/">

                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <br/>
                <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
            </form>
            {% endif %}
            </div>
        </div>
</div>
    {% endblock %}

recipes_project/templates/recipes/add_ingredient.html
{% extends 'recipes/base.html' %}


{% block body_block %}
<div class="hero-unit">
    <h1>Add Ingredient</h1>
    <br>
    <div class="container">
        <form class="span6" id="ingredient_form" method="post" >

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field }}
                {{ field.help_text }}
                <br/>
            {% endfor %}

            <button class="btn btn-primary" type="submit" name="submit">Add Ingredient</button>
            <script type="text/javascript">$("#id_name").focus()</script>
        </form>
    </div>
</div>
{% endblock %}

recipes_project/templates/recipes/add_page.html
{% extends 'recipes/base.html' %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
<div class="hero-unit">
        <h1>Add a Page</h1>
<br>
<div class="container">
        {% if not category_name_url %}
            <div style="color: red;">The specified page does not exist!</div>
        {% else %}
        <form class="span6" id="page_form" method="post" action="/category/{{ category_name_url }}/add_page/">

                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                    <br/>

                    <button class="btn btn-primary" type="submit" name="submit">Add a Page</button>
            </form>
        {% endif %}
        </div>
    </div>
</div>
    {% endblock %}

recipes_project/templates/recipes/add_recipe_ingredient.html
{% extends 'recipes/base.html' %}

{% block title %}{{ recipe.title }}{% endblock %}

{% block body_block %}
<div class="hero-unit">
    <h1>{{ recipe.title }}</h1>
    <br>
<div>
            <ul>
            {% for ingredient in recipe.ingredients.all %}
            <li>{{ ingredient }}</li>
            {% endfor %}
            </ul>
</div>
    <div class="container">
        <form class="span6" id="recipe_ingredient_form" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit" name="submit">Add Ingredient</button>
        </form>
    </div>

</div>
{% endblock %}

recipes_project/templates/recipes/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'js/jquery-2.1.0.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/recipes-ajax.js' %}"></script>
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css'%}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Ubuntu+Condensed|Vollkorn:400,700,400italic' rel='stylesheet' type='text/css'>
    <title>Recipes - {% block title %}A Collection{% endblock %}</title>
    </head>

    <body>
<div class="navbar navbar-inverse navbar-fixed-top">
   <div class="navbar-inner">
       <div class="container">
           <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
           </button>
           <a class="brand" href="/">Recipes</a></li>
           <div class="nav-collapse collapse">
               <ul class="nav pull-right">
                    {% if user.is_authenticated %}
                    <li class="navbar-text">Welcome, {{ user.username }}!</li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'register' %}">Register</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>
                <ul class="nav">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'add_category' %}">Add a New Category</a></li>
                    <li><a href="{% url 'profile' %}">Profile</a></li>
                    {% endif %}

                    <li><a href="{% url 'about' %}">About</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
            		<img src="{% static "cucumber.png" %}" alt"cucumber" />
                <!--- Empty for the timebeing -->
                <ul class="nav nav-list">
                    <li style="font-family: Ubunto; class="nav-header">Find a Category</li>
                    <form>
                    <label></label>
                    <li><input  class="search-query span10" type="text"
                        name="suggestion" value="" id="suggestion" /></li>
                    </form>
                </ul>
        {% if cat_list %}
        <div id="cats">
            {% include 'recipes/category_list.html' with cat_list=cat_list %}
        </div>
        {% endif %}
                {% block sidebar %}
                {% endblock %}
                <div id="cats">
                    {% if cat_list %}
                        <ul class="nav nav-list"><li>Category List</li></ul>
                        {% include 'recipes/category_list.html' with cat_list=cat_list %}
                    {% endif %}
                </div>
            </div>
            <!--/.well -->
        </div>
        <!--/span-->
        <div class="span9">
            {% block body_block %}
            {% endblock %}
        </div>
        <!--/span-->
    </div>
    <!--/row-->
</div>
<!--/.fluid-container-->
<br>
<br>
<br>
<br>
<br>
<br>

<hr>
<footer>
    <div class="container">
        <p>&copy; Recipes: A Collection from Here and There 2014</p>
    </div>
</footer>
    </body>
</html>

recipes_project/templates/recipes/category.html
{% extends 'recipes/base.html' %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
<div class="hero-unit">
        <h1>{{ category_name }}</h1>
    <div class="container-fluid">
        <p>Search for a recipe</p>
        <form class="form-search span8" id="search_form" method="post">
            {% csrf_token %}
            <!-- Display the search form elements here -->
            <input type="text" class="input-long search-query" name="query"
                data-catid="{{category.id}}" value="{{ query }}" id="recipe_suggest" />
            <button class="btn btn-primary" type="submit" name="submit"
                value="Search" />Search</button>
            <br />
        </form>
    </div>
    {% if query %}
    <div class="container-fluid">
        {% if result_list %}
            <!-- Display search results in an ordered list -->
            <ol>
                {% for result in result_list %}
                <li>
        {% if user.is_authenticated %}
        <button data-catid="{{category.id}}" data-title="{{ result.title }}"
            data-url="{{ result.link }}" class="recipes-add btn btn-mini btn-info"
            type="button">Add</button>
        {% endif %}

                    <strong><a href="{{ result.link }}">{{ result.title }}</a></strong><br />
                    <p>{{ result.summary }}</p>
                </li>
                {% endfor %}
            </ol>
        {% else %}
            <br/>
            <p>No results found</p>
        {% endif %}
    </div>
    {% endif %}
<div>
<p>

<b id="like_count">{{ category.likes }}</b> people like this category

{% if user.is_authenticated %}
        <button id="likes" data-catid="{{category.id}}" class="btn btn-mini btn-primary" type="button">Like</button>
{% endif %}

</p>
</div>
<div id="recps">{%  include 'recipes/recipe_list.html' %}</div>
            {% if user.is_authenticated %}
            <a href="{% url 'add_recipe' %}" class="btn btn-primary btn-lg" role="button">Add a Recipe</a>
            {% endif %}
</div>
{% endblock %}

recipes_project/templates/recipes/category_list.html
<ul class="nav nav-list">
    {% if cat_list %}
        {% for cat in cat_list %}
        <li><a href="{% url 'category' cat.url %}">{{ cat.name }}</a></li>
        {% endfor %}
    {% else %}
        <li>No categories at present.</li>
   {% endif %}
</ul>

recipes_project/templates/recipes/index.html
{% extends 'recipes/base.html' %}

{% block title %}Lisa's Recipe Page{% endblock %}
{% block body_block %}
<div class="hero-unit">
    <h1></h1>
    <img src="static/dinnertitle3.jpg" alt"colorful salad" />
    <p style="font-family: Ubunto; color: #7a6f66; font-size: 1.25em";>Find, Add, Share Recipes, Useful Links and Resources.</p>
        <form class="form-search span8" id="search_form" method="post">
            {% csrf_token %}
            <!-- Display the search form elements here -->
            <input type="text" class="input-long search-query" name="query"
                value="{{ query }}" id="recipe_suggest" />
            <button class="btn btn-primary" type="submit" name="submit"
                value="Search" />Search</button>                                                                   <br />                                                                                             </form>
</div>

{% if query %}                                                                                         <div class="container-fluid">
        {% if result_list %}                                                                                       <!-- Display search results in an ordered list -->                                                     <ol>
                {% for result in result_list %}                                                                        <li>                                                                                           {% if user.is_authenticated %}
        <button data-catid="{{category.id}}" data-title="{{ result.title }}"                                       data-url="{{ result.link }}" class="recipes-add btn btn-mini btn-info"                                 type="button">Add</button>
        {% endif %}                                                                                                                                                                                                               <strong><a href="{{ result.link }}">{{ result.title }}</a></strong><br />
                    <p>{{ result.summary }}</p>                                                                        </li>                                                                                                  {% endfor %}
            </ol>
        {% else %}
            <br/>
            <p>No results found</p>
        {% endif %}
    </div>
    {% endif %}

<div class="row-fluid">
    <div id="recps">
        
    <div class="span6">
        <h2 style="font-family: Ubunto";>Top Five Categories</h2>
        {% if categories %}
        <ul>
            {% for category in categories %}
            <li><a href="{% url 'category' category.url %}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No categories at present.</strong>
        {% endif %}

    </div>
    <!--/span-->
    <div class="span6">
        <h2 style="font-family: Ubunto";>Top Five Recipes</h2>
        {% if recipes %}
        <ul>
            {% for recipe in recipes %}
            <li><a href="{% url 'recipe' recipe.id %}">{{ recipe.title }}</a> - {{ recipe.category }} ({{ recipe.views }} view(s))</li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No recipes at present.</strong>
        {% endif %}

    </div>
</div>
    <!--/span-->
</div>
<!--/row-->
{% endblock %}